### ISSUE TITLE
interval, sync_duration

### ISSUE THREAD

**Issue by vgeannin** [nokia/OSSMediator#44]
Hi All,

can you explain me the meaning of those two value  :
    {
      "api": "/network-hardware-groups/{nhg_id}/fmdata",
      "type": "ACTIVE",
      "metric_type": "CORE",
      **"interval": 30,
      "sync_duration": 15**
    }
Does it mean that we retrieve fmdata every 30minutes ?

Thanks,
Vincent

**Comment by soursing** [comment]
`"interval": 30` :Interval at which API will be called to collect data. In this case `fmdata` API will be called every `30m` to get the list of `ACTIVE` `CORE` alarms.  

`"sync_duration": 15` : OSSMediator tries to sync alarm so that none of the alarms should be missed in the API. `sync_duration` denotes time duration for syncing the alarms, in this case alarms will be fetched between `last alarm received time - 15m` to `current time`.

**NOTE**: `sync_duration` is not used for ACTIVE alarm type, it is only used for HISTORY alarms, we'll remove it from configuration.

**Comment by vgeannin** [comment]
Thanks,

Just another question, what is the impact if we change this value from 30 to 15 ? (why do you choose 30?)

Vincent

**Comment by soursing** [comment]
fmdata API has below mentioned functionality:  
- `fmdata HISTORY API` is configured to be called every `1m`, it fetches both active and cleared alarms for the duration `last alarm received time - sync_duration to current time`.
   `{
      "api": "/network-hardware-groups/{nhg_id}/fmdata",
      "type": "HISTORY",
      "metric_type": "CORE",
      "interval": 1,
      "sync_duration": 15
    }`
- `fmdata ACTIVE API` is configured to be called every `30m`, it fetches all the active alarms for the network.
   `{
      "api": "/network-hardware-groups/{nhg_id}/fmdata",
      "type": "ACTIVE",
      "metric_type": "CORE",
      "interval": 30
    }`

Changing the frequency from 30m to 15m will not have much impact, as `fmdata HISTORY API` gets the active alarms also, we don't need to call `fmdata  ACTIVE API` frequently. So we kept the frequency to 30m to sync the ACTIVE alarms properly.
